### ISSUE TITLE
need help with bip39

### ISSUE THREAD

**Issue by nft30001** [PawelGorny/WifSolver#3]
back in 2016 i created BTC account and funded 2 BTC. i wrote bip39 but did not saved wallet file. years passed and back in 2019 i tried to find paper but i come to know i have lost it. i only remember first 3 words and last one but have no idea regarding other words . i tried to use lot of tools but its impossible to solve i guess. i am using now FinderOuter but i know this will take centuries maybe lol. than i saw a program WIfGPU solver but noob in programing don't have any idea how this will work on windows 10. can you compile for me maybe this will help me out maybe in good speed. one thing my wallet is having 1 + 1 btc in first 2 addresses and i have to load 2 address but FinderOuter only allow 1 address. any help will be highly appreciated

**Comment by PawelGorny** [comment]
Hello,
This comment should be more under my other project: https://github.com/PawelGorny/lostword
How many words are in your seed? 12? 24? 8 missing is already a lot and it does not look optimistic. Do not you have any other clues? At least if words were short, long, starting letter?
You do not need to search for 2 addresses, you may search for one and then just indicate that it is first or second address. When you receive seed, you will have access to both addresses.
