### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by Handsomekaizer** [PawelGorny/WifSolver#5]
Hello sir 
I love this work in particular and I wanted to use it to recover my missing compressed private key with 10 characters missing but the problem is I am new to java, so I was wondering if you could help me make this into an Android app or host it on heroku, netlify or vercel. Please, if you help me I will donate 2 BTC. Please

**Comment by PawelGorny** [comment]
Please email me (pawgo@protonmail.com) for details, I do not understand what do you want to "host on heroku" etc.

**Comment by Handsomekaizer** [comment]
Can you make this Wifsolver in another language like in JavaScript, php, typescript, html. Or can you build it like an Android app

**Comment by Handsomekaizer** [comment]
Can you run it here https://replit.com/~

**Comment by PawelGorny** [comment]
https://replit.com/@PawelGorny1/WifSolver#.replit -> RUN for build

And then in the console launch:
cd target
java -jar wifSolver-jar-with-dependencies.jar ../examples/example_END.conf2

Please refer to other examples to see how to configure launch for your problem.
