### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Handsomekaizer** [PawelGorny/WifSolver#7]
Hello again sir
Your tool worked perfectly but it is very slow and at the rate it is working it will take me ages to recover the 10 missing characters. Please can you make it faster.
I am actually using WifSolver/examples/example_SEARCH.conf3

**Comment by PawelGorny** [comment]
Improved in version 0.5.11
please test with file "examples/example_END.conf3"(https://github.com/PawelGorny/WifSolver/blob/master/examples/example_END.conf3)

Now, missing 10 characters are solved almost instantly

**Comment by Handsomekaizer** [comment]
This is what my missing private key looks like
L5**********5byuThiS5sEGMpmcRZdPAhmWLRfMmutGmPHtjKrp
It is not missing characters at the end
